version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: hydronix
      POSTGRES_PASSWORD: hydronix_pass
      POSTGRES_DB: hydronix_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  backend:
    build: ./backend
    depends_on:
      - db
      - ml-service
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+psycopg2://hydronix:hydronix_pass@db:5432/hydronix_db
      MQTT_BROKER: broker.hivemq.com
      MQTT_PORT: 1883
      ML_SERVICE_URL: http://ml-service:8000
  ml-service:
    build: ./ml-service
    ports:
      - "8001:8000"
    depends_on:
      - db
    volumes:
      - ./ML-Model/models:/app/models:ro
volumes:
  db_data:
