"""initial

Revision ID: 7238bc77b1a1
Revises: 
Create Date: 2026-06-20 01:05:49.409511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7238bc77b1a1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('sensor_data_2026_08_device_id_idx', table_name='sensor_data_2026_08')
    op.drop_index('sensor_data_2026_08_device_id_timestamp_idx', table_name='sensor_data_2026_08')
    op.drop_index('sensor_data_2026_08_timestamp_idx', table_name='sensor_data_2026_08')
    op.drop_table('sensor_data_2026_08')
    op.drop_index('sensor_data_2026_10_device_id_idx', table_name='sensor_data_2026_10')
    op.drop_index('sensor_data_2026_10_device_id_timestamp_idx', table_name='sensor_data_2026_10')
    op.drop_index('sensor_data_2026_10_timestamp_idx', table_name='sensor_data_2026_10')
    op.drop_table('sensor_data_2026_10')
    op.drop_index('sensor_data_2026_07_device_id_idx', table_name='sensor_data_2026_07')
    op.drop_index('sensor_data_2026_07_device_id_timestamp_idx', table_name='sensor_data_2026_07')
    op.drop_index('sensor_data_2026_07_timestamp_idx', table_name='sensor_data_2026_07')
    op.drop_table('sensor_data_2026_07')
    op.drop_index('sensor_data_2026_11_device_id_idx', table_name='sensor_data_2026_11')
    op.drop_index('sensor_data_2026_11_device_id_timestamp_idx', table_name='sensor_data_2026_11')
    op.drop_index('sensor_data_2026_11_timestamp_idx', table_name='sensor_data_2026_11')
    op.drop_table('sensor_data_2026_11')
    op.drop_index('sensor_data_2027_01_device_id_idx', table_name='sensor_data_2027_01')
    op.drop_index('sensor_data_2027_01_device_id_timestamp_idx', table_name='sensor_data_2027_01')
    op.drop_index('sensor_data_2027_01_timestamp_idx', table_name='sensor_data_2027_01')
    op.drop_table('sensor_data_2027_01')
    op.drop_index('sensor_data_2026_06_device_id_idx', table_name='sensor_data_2026_06')
    op.drop_index('sensor_data_2026_06_device_id_timestamp_idx', table_name='sensor_data_2026_06')
    op.drop_index('sensor_data_2026_06_timestamp_idx', table_name='sensor_data_2026_06')
    op.drop_table('sensor_data_2026_06')
    op.drop_index('sensor_data_2026_12_device_id_idx', table_name='sensor_data_2026_12')
    op.drop_index('sensor_data_2026_12_device_id_timestamp_idx', table_name='sensor_data_2026_12')
    op.drop_index('sensor_data_2026_12_timestamp_idx', table_name='sensor_data_2026_12')
    op.drop_table('sensor_data_2026_12')
    op.drop_index('sensor_data_2027_03_device_id_idx', table_name='sensor_data_2027_03')
    op.drop_index('sensor_data_2027_03_device_id_timestamp_idx', table_name='sensor_data_2027_03')
    op.drop_index('sensor_data_2027_03_timestamp_idx', table_name='sensor_data_2027_03')
    op.drop_table('sensor_data_2027_03')
    op.drop_index('sensor_data_2027_02_device_id_idx', table_name='sensor_data_2027_02')
    op.drop_index('sensor_data_2027_02_device_id_timestamp_idx', table_name='sensor_data_2027_02')
    op.drop_index('sensor_data_2027_02_timestamp_idx', table_name='sensor_data_2027_02')
    op.drop_table('sensor_data_2027_02')
    op.drop_index('sensor_data_2027_04_device_id_idx', table_name='sensor_data_2027_04')
    op.drop_index('sensor_data_2027_04_device_id_timestamp_idx', table_name='sensor_data_2027_04')
    op.drop_index('sensor_data_2027_04_timestamp_idx', table_name='sensor_data_2027_04')
    op.drop_table('sensor_data_2027_04')
    op.drop_index('sensor_data_2026_09_device_id_idx', table_name='sensor_data_2026_09')
    op.drop_index('sensor_data_2026_09_device_id_timestamp_idx', table_name='sensor_data_2026_09')
    op.drop_index('sensor_data_2026_09_timestamp_idx', table_name='sensor_data_2026_09')
    op.drop_table('sensor_data_2026_09')
    op.drop_index('sensor_data_2027_05_device_id_idx', table_name='sensor_data_2027_05')
    op.drop_index('sensor_data_2027_05_device_id_timestamp_idx', table_name='sensor_data_2027_05')
    op.drop_index('sensor_data_2027_05_timestamp_idx', table_name='sensor_data_2027_05')
    op.drop_table('sensor_data_2027_05')
    op.add_column('devices', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('devices', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'longitude')
    op.drop_column('devices', 'latitude')
    op.create_table('sensor_data_2027_05',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('device_reset_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('seq_no', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('ph', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('turbidity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('tds', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('temperature', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('flow_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('raw_ph', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('quality_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('anomaly_flags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('received_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('timestamp_source', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('trace_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('valve_state', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('valve_last_toggled', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.CheckConstraint("timestamp_source::text = ANY (ARRAY['device'::character varying, 'server_adjusted'::character varying, 'server_only'::character varying]::text[])", name='check_timestamp_source'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.device_id'], name='sensor_data_device_id_fkey'),
    sa.PrimaryKeyConstraint('id', 'timestamp', name='sensor_data_2027_05_pkey'),
    sa.UniqueConstraint('device_id', 'device_reset_count', 'seq_no', 'timestamp', name='sensor_data_2027_05_device_id_device_reset_count_seq_no_tim_key')
    )
    op.create_index('sensor_data_2027_05_timestamp_idx', 'sensor_data_2027_05', ['timestamp'], unique=False)
    op.create_index('sensor_data_2027_05_device_id_timestamp_idx', 'sensor_data_2027_05', ['device_id', 'timestamp'], unique=False)
    op.create_index('sensor_data_2027_05_device_id_idx', 'sensor_data_2027_05', ['device_id'], unique=False)
    op.create_table('sensor_data_2026_09',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('device_reset_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('seq_no', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('ph', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('turbidity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('tds', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('temperature', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('flow_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('raw_ph', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('quality_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('anomaly_flags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('received_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('timestamp_source', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('trace_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('valve_state', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('valve_last_toggled', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.CheckConstraint("timestamp_source::text = ANY (ARRAY['device'::character varying, 'server_adjusted'::character varying, 'server_only'::character varying]::text[])", name='check_timestamp_source'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.device_id'], name='sensor_data_device_id_fkey'),
    sa.PrimaryKeyConstraint('id', 'timestamp', name='sensor_data_2026_09_pkey'),
    sa.UniqueConstraint('device_id', 'device_reset_count', 'seq_no', 'timestamp', name='sensor_data_2026_09_device_id_device_reset_count_seq_no_tim_key')
    )
    op.create_index('sensor_data_2026_09_timestamp_idx', 'sensor_data_2026_09', ['timestamp'], unique=False)
    op.create_index('sensor_data_2026_09_device_id_timestamp_idx', 'sensor_data_2026_09', ['device_id', 'timestamp'], unique=False)
    op.create_index('sensor_data_2026_09_device_id_idx', 'sensor_data_2026_09', ['device_id'], unique=False)
    op.create_table('sensor_data_2027_04',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('device_reset_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('seq_no', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('ph', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('turbidity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('tds', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('temperature', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('flow_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('raw_ph', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('quality_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('anomaly_flags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('received_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('timestamp_source', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('trace_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('valve_state', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('valve_last_toggled', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.CheckConstraint("timestamp_source::text = ANY (ARRAY['device'::character varying, 'server_adjusted'::character varying, 'server_only'::character varying]::text[])", name='check_timestamp_source'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.device_id'], name='sensor_data_device_id_fkey'),
    sa.PrimaryKeyConstraint('id', 'timestamp', name='sensor_data_2027_04_pkey'),
    sa.UniqueConstraint('device_id', 'device_reset_count', 'seq_no', 'timestamp', name='sensor_data_2027_04_device_id_device_reset_count_seq_no_tim_key')
    )
    op.create_index('sensor_data_2027_04_timestamp_idx', 'sensor_data_2027_04', ['timestamp'], unique=False)
    op.create_index('sensor_data_2027_04_device_id_timestamp_idx', 'sensor_data_2027_04', ['device_id', 'timestamp'], unique=False)
    op.create_index('sensor_data_2027_04_device_id_idx', 'sensor_data_2027_04', ['device_id'], unique=False)
    op.create_table('sensor_data_2027_02',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('device_reset_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('seq_no', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('ph', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('turbidity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('tds', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('temperature', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('flow_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('raw_ph', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('quality_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('anomaly_flags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('received_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('timestamp_source', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('trace_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('valve_state', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('valve_last_toggled', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.CheckConstraint("timestamp_source::text = ANY (ARRAY['device'::character varying, 'server_adjusted'::character varying, 'server_only'::character varying]::text[])", name='check_timestamp_source'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.device_id'], name='sensor_data_device_id_fkey'),
    sa.PrimaryKeyConstraint('id', 'timestamp', name='sensor_data_2027_02_pkey'),
    sa.UniqueConstraint('device_id', 'device_reset_count', 'seq_no', 'timestamp', name='sensor_data_2027_02_device_id_device_reset_count_seq_no_tim_key')
    )
    op.create_index('sensor_data_2027_02_timestamp_idx', 'sensor_data_2027_02', ['timestamp'], unique=False)
    op.create_index('sensor_data_2027_02_device_id_timestamp_idx', 'sensor_data_2027_02', ['device_id', 'timestamp'], unique=False)
    op.create_index('sensor_data_2027_02_device_id_idx', 'sensor_data_2027_02', ['device_id'], unique=False)
    op.create_table('sensor_data_2027_03',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('device_reset_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('seq_no', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('ph', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('turbidity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('tds', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('temperature', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('flow_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('raw_ph', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('quality_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('anomaly_flags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('received_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('timestamp_source', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('trace_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('valve_state', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('valve_last_toggled', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.CheckConstraint("timestamp_source::text = ANY (ARRAY['device'::character varying, 'server_adjusted'::character varying, 'server_only'::character varying]::text[])", name='check_timestamp_source'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.device_id'], name='sensor_data_device_id_fkey'),
    sa.PrimaryKeyConstraint('id', 'timestamp', name='sensor_data_2027_03_pkey'),
    sa.UniqueConstraint('device_id', 'device_reset_count', 'seq_no', 'timestamp', name='sensor_data_2027_03_device_id_device_reset_count_seq_no_tim_key')
    )
    op.create_index('sensor_data_2027_03_timestamp_idx', 'sensor_data_2027_03', ['timestamp'], unique=False)
    op.create_index('sensor_data_2027_03_device_id_timestamp_idx', 'sensor_data_2027_03', ['device_id', 'timestamp'], unique=False)
    op.create_index('sensor_data_2027_03_device_id_idx', 'sensor_data_2027_03', ['device_id'], unique=False)
    op.create_table('sensor_data_2026_12',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('device_reset_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('seq_no', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('ph', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('turbidity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('tds', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('temperature', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('flow_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('raw_ph', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('quality_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('anomaly_flags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('received_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('timestamp_source', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('trace_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('valve_state', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('valve_last_toggled', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.CheckConstraint("timestamp_source::text = ANY (ARRAY['device'::character varying, 'server_adjusted'::character varying, 'server_only'::character varying]::text[])", name='check_timestamp_source'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.device_id'], name='sensor_data_device_id_fkey'),
    sa.PrimaryKeyConstraint('id', 'timestamp', name='sensor_data_2026_12_pkey'),
    sa.UniqueConstraint('device_id', 'device_reset_count', 'seq_no', 'timestamp', name='sensor_data_2026_12_device_id_device_reset_count_seq_no_tim_key')
    )
    op.create_index('sensor_data_2026_12_timestamp_idx', 'sensor_data_2026_12', ['timestamp'], unique=False)
    op.create_index('sensor_data_2026_12_device_id_timestamp_idx', 'sensor_data_2026_12', ['device_id', 'timestamp'], unique=False)
    op.create_index('sensor_data_2026_12_device_id_idx', 'sensor_data_2026_12', ['device_id'], unique=False)
    op.create_table('sensor_data_2026_06',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('device_reset_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('seq_no', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('ph', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('turbidity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('tds', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('temperature', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('flow_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('raw_ph', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('quality_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('anomaly_flags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('received_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('timestamp_source', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('trace_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('valve_state', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('valve_last_toggled', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.CheckConstraint("timestamp_source::text = ANY (ARRAY['device'::character varying, 'server_adjusted'::character varying, 'server_only'::character varying]::text[])", name='check_timestamp_source'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.device_id'], name='sensor_data_device_id_fkey'),
    sa.PrimaryKeyConstraint('id', 'timestamp', name='sensor_data_2026_06_pkey'),
    sa.UniqueConstraint('device_id', 'device_reset_count', 'seq_no', 'timestamp', name='sensor_data_2026_06_device_id_device_reset_count_seq_no_tim_key')
    )
    op.create_index('sensor_data_2026_06_timestamp_idx', 'sensor_data_2026_06', ['timestamp'], unique=False)
    op.create_index('sensor_data_2026_06_device_id_timestamp_idx', 'sensor_data_2026_06', ['device_id', 'timestamp'], unique=False)
    op.create_index('sensor_data_2026_06_device_id_idx', 'sensor_data_2026_06', ['device_id'], unique=False)
    op.create_table('sensor_data_2027_01',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('device_reset_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('seq_no', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('ph', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('turbidity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('tds', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('temperature', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('flow_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('raw_ph', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('quality_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('anomaly_flags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('received_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('timestamp_source', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('trace_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('valve_state', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('valve_last_toggled', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.CheckConstraint("timestamp_source::text = ANY (ARRAY['device'::character varying, 'server_adjusted'::character varying, 'server_only'::character varying]::text[])", name='check_timestamp_source'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.device_id'], name='sensor_data_device_id_fkey'),
    sa.PrimaryKeyConstraint('id', 'timestamp', name='sensor_data_2027_01_pkey'),
    sa.UniqueConstraint('device_id', 'device_reset_count', 'seq_no', 'timestamp', name='sensor_data_2027_01_device_id_device_reset_count_seq_no_tim_key')
    )
    op.create_index('sensor_data_2027_01_timestamp_idx', 'sensor_data_2027_01', ['timestamp'], unique=False)
    op.create_index('sensor_data_2027_01_device_id_timestamp_idx', 'sensor_data_2027_01', ['device_id', 'timestamp'], unique=False)
    op.create_index('sensor_data_2027_01_device_id_idx', 'sensor_data_2027_01', ['device_id'], unique=False)
    op.create_table('sensor_data_2026_11',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('device_reset_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('seq_no', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('ph', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('turbidity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('tds', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('temperature', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('flow_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('raw_ph', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('quality_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('anomaly_flags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('received_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('timestamp_source', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('trace_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('valve_state', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('valve_last_toggled', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.CheckConstraint("timestamp_source::text = ANY (ARRAY['device'::character varying, 'server_adjusted'::character varying, 'server_only'::character varying]::text[])", name='check_timestamp_source'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.device_id'], name='sensor_data_device_id_fkey'),
    sa.PrimaryKeyConstraint('id', 'timestamp', name='sensor_data_2026_11_pkey'),
    sa.UniqueConstraint('device_id', 'device_reset_count', 'seq_no', 'timestamp', name='sensor_data_2026_11_device_id_device_reset_count_seq_no_tim_key')
    )
    op.create_index('sensor_data_2026_11_timestamp_idx', 'sensor_data_2026_11', ['timestamp'], unique=False)
    op.create_index('sensor_data_2026_11_device_id_timestamp_idx', 'sensor_data_2026_11', ['device_id', 'timestamp'], unique=False)
    op.create_index('sensor_data_2026_11_device_id_idx', 'sensor_data_2026_11', ['device_id'], unique=False)
    op.create_table('sensor_data_2026_07',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('device_reset_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('seq_no', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('ph', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('turbidity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('tds', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('temperature', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('flow_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('raw_ph', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('quality_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('anomaly_flags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('received_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('timestamp_source', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('trace_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('valve_state', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('valve_last_toggled', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.CheckConstraint("timestamp_source::text = ANY (ARRAY['device'::character varying, 'server_adjusted'::character varying, 'server_only'::character varying]::text[])", name='check_timestamp_source'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.device_id'], name='sensor_data_device_id_fkey'),
    sa.PrimaryKeyConstraint('id', 'timestamp', name='sensor_data_2026_07_pkey'),
    sa.UniqueConstraint('device_id', 'device_reset_count', 'seq_no', 'timestamp', name='sensor_data_2026_07_device_id_device_reset_count_seq_no_tim_key')
    )
    op.create_index('sensor_data_2026_07_timestamp_idx', 'sensor_data_2026_07', ['timestamp'], unique=False)
    op.create_index('sensor_data_2026_07_device_id_timestamp_idx', 'sensor_data_2026_07', ['device_id', 'timestamp'], unique=False)
    op.create_index('sensor_data_2026_07_device_id_idx', 'sensor_data_2026_07', ['device_id'], unique=False)
    op.create_table('sensor_data_2026_10',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('device_reset_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('seq_no', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('ph', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('turbidity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('tds', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('temperature', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('flow_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('raw_ph', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('quality_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('anomaly_flags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('received_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('timestamp_source', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('trace_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('valve_state', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('valve_last_toggled', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.CheckConstraint("timestamp_source::text = ANY (ARRAY['device'::character varying, 'server_adjusted'::character varying, 'server_only'::character varying]::text[])", name='check_timestamp_source'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.device_id'], name='sensor_data_device_id_fkey'),
    sa.PrimaryKeyConstraint('id', 'timestamp', name='sensor_data_2026_10_pkey'),
    sa.UniqueConstraint('device_id', 'device_reset_count', 'seq_no', 'timestamp', name='sensor_data_2026_10_device_id_device_reset_count_seq_no_tim_key')
    )
    op.create_index('sensor_data_2026_10_timestamp_idx', 'sensor_data_2026_10', ['timestamp'], unique=False)
    op.create_index('sensor_data_2026_10_device_id_timestamp_idx', 'sensor_data_2026_10', ['device_id', 'timestamp'], unique=False)
    op.create_index('sensor_data_2026_10_device_id_idx', 'sensor_data_2026_10', ['device_id'], unique=False)
    op.create_table('sensor_data_2026_08',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('device_reset_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('seq_no', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('ph', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('turbidity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('tds', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('temperature', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('flow_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('raw_ph', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('quality_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('anomaly_flags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('received_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('timestamp_source', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('trace_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('valve_state', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('valve_last_toggled', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.CheckConstraint("timestamp_source::text = ANY (ARRAY['device'::character varying, 'server_adjusted'::character varying, 'server_only'::character varying]::text[])", name='check_timestamp_source'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.device_id'], name='sensor_data_device_id_fkey'),
    sa.PrimaryKeyConstraint('id', 'timestamp', name='sensor_data_2026_08_pkey'),
    sa.UniqueConstraint('device_id', 'device_reset_count', 'seq_no', 'timestamp', name='sensor_data_2026_08_device_id_device_reset_count_seq_no_tim_key')
    )
    op.create_index('sensor_data_2026_08_timestamp_idx', 'sensor_data_2026_08', ['timestamp'], unique=False)
    op.create_index('sensor_data_2026_08_device_id_timestamp_idx', 'sensor_data_2026_08', ['device_id', 'timestamp'], unique=False)
    op.create_index('sensor_data_2026_08_device_id_idx', 'sensor_data_2026_08', ['device_id'], unique=False)
    # ### end Alembic commands ###
